# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jm1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, QDateTime
import PhotoresistorAndInfrared as oj
import threading
#总检测
#光敏电阻:check=0一定时间无瓶子递入 check=1瓶子有标签 check=2瓶子无标签
#红外线: check=3 有东西经过


thread = threading.Thread(target=oj.loop)

# '''p = vlc.MediaPlayer("file:C:\\Users\\ASUS\\Desktop\\hygl.mp3")
# b = vlc.MediaPlayer("file:C:\\Users\\ASUS\\Desktop\\hygl.mp3")'''

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1122, 849)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 400, 401, 291))
        self.pushButton.setObjectName("pushButton")

        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(340, 400, 401, 291))
        self.pushButton2.setObjectName("pushButton")
        self.pushButton2.setVisible(False)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(480, 80, 211, 271))
        self.label.setObjectName("label")

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 26))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.count = 7
        self.time = QTimer()
        self.time.setInterval(1000)
        self.time.timeout.connect(self.Refresh)

        self.pushButton.clicked.connect(self.click_success1)
        self.pushButton2.clicked.connect(self.click_success2)
        '''self.time.timeout.connect(self.Refresh2)'''
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "收垃圾收pet瓶"))
        self.pushButton.setText(_translate("MainWindow", "我要投瓶"))
        self.label.setText(_translate("MainWindow", "这是宣传片宣传片宣传片"))

    def click_success1(self):
        _translate = QtCore.QCoreApplication.translate
        self.time.start()
        self.label.setText(_translate("MainWindow", "这是温馨提示温馨提示温馨提示"))
        self.pushButton.setEnabled(False)
        '''p.play()'''

        oj.sta = 1
#        oj.loop()
        thread.start()

    def click_success2(self):
        _translate = QtCore.QCoreApplication.translate
        self.time.start()
        self.label.setText(_translate("MainWindow", "谢谢您"))
        self.pushButton2.setVisible(False)
        self.pushButton.setEnabled(True)
        
        oj.sta=0
#        thread.join()
        oj.destroy

    def Refresh(self):
        _translate = QtCore.QCoreApplication.translate
        if self.count > 0:
            self.pushButton.setText(str(self.count))
            self.count -= 1
        else:
            self.time.stop()
            if self.pushButton.isEnabled()==False:
                self.pushButton.setVisible(False)
                self.pushButton2.setText(_translate("MainWindow", "我投完了"))
                self.pushButton2.setVisible(True)
                self.count = 7
            else:
                self.pushButton.setVisible(True)
                self.pushButton.setEnabled(True)
                self.label.setText(_translate("MainWindow", "这是宣传片宣传片宣传片"))
                self.pushButton.setText(_translate("MainWindow", "我要投瓶"))
                thread.join()
                self.count = 2
                




    '''def Refresh2(self):
        if self.count > 0:
            self.count -= 1
        else:
            self.time.stop()
            self.setupUi(self,self.MainWindow)'''